"""add simulation runs

Revision ID: 43f73403f5d2
Revises: a8ae1aa42ced
Create Date: 2026-01-02 13:03:54.963599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f73403f5d2'
down_revision: Union[str, Sequence[str], None] = 'a8ae1aa42ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'success', 'failed', name='simulationstatus'), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
